### ISSUE TITLE
bug解决方式

### ISSUE THREAD

**Issue by chengzhaobin** [354476429/nacos-bug#1]
有解决方案吗？

**Comment by 354476429** [comment]
提ISSUES问了官方团队,这个应该不算是BUG,算是使用不当造成的,在注入NacosRule的时候默认是单例所以会出问题,所以只需要设置成多例的就OK了.
注入代码如下:
`    
@Bean
    @Scope("prototype")
    public IRule clusterLoadBalancerRule(){
        return new NacosRule();
    }
`

**Comment by chengzhaobin** [comment]
非常感谢
